buildVariant:
        description: 'Select Build Variant'
        required: true
        default: 'EngineeringRelease'
        type: choice
        options:
          - EngineeringRelease
          - EngineeringDebug
          - fullRelease
          - fullDebug
          - aapsclientRelease
          - aapsclientDebug
          - aapsclient2Release
          - aapsclient2Debug
          - pumpcontrolRelease
          - pumpcontrolDebug
